# Generated by Django 4.2.3 on 2023-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default=1, verbose_name='About Product'),
            preserve_default=False,
        ),
    ]
