# Generated by Django 4.2.3 on 2023-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.TextField(default='hello', verbose_name='About Product'),
            preserve_default=False,
        ),
    ]
